### ISSUE TITLE
License question and Package.json 

### ISSUE THREAD

**Issue by hrieke** [iterativelyhq/itly-sdk#64]
Hi guys,

You have the MIT License file as your license text, but in the package.json files you show the ISC License.  Small but important differences between the two, can you fix one or the other?

Secondly, you do not list here as the homepage / source code repo of choice.
When I (or anyone else) would need to report an issue, first we need to perform a quick search.
It would be great to see the repo / home page / issues listed in the NPM page.
For example:
https://www.npmjs.com/package/@itly/plugin-snowplow-react-native

vs.
https://www.npmjs.com/package/classnames

(Package.json contains the following lines:
```
  "repository": {
    "type": "git",
    "url": "https://github.com/JedWatson/classnames.git"
  },
```

)

Thank You and Keep on Rocking!

**Comment by justin-iteratively** [comment]
Hi @hrieke, thanks for bringing this to our attention. 

We published a new version `2.0.9` today and all packages now have:
* MIT license
* Repo and home page links

e.g. [@itly/plugin-snowplow-react-native](https://www.npmjs.com/package/@itly/plugin-snowplow-react-native)

Thanks for helping improve the product!
